### ISSUE TITLE
Error running habitrello ("AttributeError: 'HabiTrello' object has no attribute 'todos_list'")

### ISSUE THREAD

**Issue by gutogarrote** [larssorenson/habitrello#2]
Hi!

Sorry if this is too much of a newbie mistake, but I can't seem to run HabiTrello.

When I run `python habitrello.py`, I get this error:

```

Traceback (most recent call last):
  File "habitrello.py", line 309, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 266, in main
    self.setup_lists()
  File "habitrello.py", line 235, in setup_lists
    self.setup_list(self.todos_list, 'Todos')
AttributeError: 'HabiTrello' object has no attribute 'todos_list'
```

I did 
```
sudo pip install --upgrade -r requirements.txt
```

I am running OSX 10.10.3
python 2.7.10

Am I doing something wrong?

Thanks.

**Comment by gutogarrote** [comment]
Hi again,

Sorry about this, but I had started everything over (for the 10th time) and I created a new Trello account to test this. This new Trello account had a different language from English.

I changed it to English and tried it again, but I still get an error.
I tried changing the date in HabitRPG to YY/mm/dd, to MM/dd/YY, to dd/mm/YY to no success.
The language in HabitRPG is English.

I noticed that the error above only happens after I run python habitrello.py for the second time (and on).

The first time I run it, after changing the name of the board in Trello, it creates the board and gives this error:

```
Traceback (most recent call last):
  File "habitrello.py", line 309, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 265, in main
    self.setup_board()
  File "habitrello.py", line 217, in setup_board
    self.board.open()
AttributeError: 'Board' object has no attribute 'open'
```

When I run it again (and again) without changing the name of the board (i.e. the board Habit RPG exists), then it archives the lists and gives the error in the first message.

I couldn't find this info, but is the date from Trello always in the %Y-%m-%d format, as in utils.py?

**Comment by larssorenson** [comment]
Hello Guto,

I'm sorry you're having issues! Unfortunately i haven't been working on 
this lately but I'll definitely take a look. I'll have to explore how 
Trello does dates to make it consistent and more robust. Also being an 
English speaker I'm a little biased, so I haven't looked into problems 
with alternate languages. Give me a couple days to make some time to 
look into these for you.

Thanks,
Lars

**Comment by larssorenson** [comment]
Hey Guto,

If you could, please try again with the latest version of the script. It seems that the script was expecting the three lists (habits, todos, and dailies) to already exist and so it wasn't adding them properly.

Please let me know if you continue having problems!

Thanks,
Lars

**Comment by gutogarrote** [comment]
Hi @larssorenson,

I've tried it and it didn't work. Then I decided to create a brand new installation (downloaded habitrello from zip, created a **new habitRPG** and **new Trello** accounts, changed both languages to English). Still no good. :(

This is what I got:

I copied the API keys from HabitRPG and Trello into keys.py and ran ```python habitrello.py```:

```
Request Token:
    - oauth_token        = a2744cd379d8bdbbb9258bab60fe4d72
    - oauth_token_secret = 143cc1c80b043956a46142d5f3f91f7b

Go to the following link in your browser:
https://trello.com/1/OAuthAuthorizeToken?oauth_token=a2744cd379d8bdbbb9258bab60fe4d72&scope=read,write&expiration=30days&name=HabiTrello
Have you authorized me? (y/n) y
What is the PIN? 8d3ba4270971b26f196af178f32f77e5
Access Token:
    - oauth_token        = 6a4abafaaa887713f2b78688f17d89c61d577181252c952a8063cee6e8308c4a
    - oauth_token_secret = 25f366264ff8a1ff8764c8ee727836fa

You may now access protected resources using the access tokens above.

Traceback (most recent call last):
  File "habitrello.py", line 312, in <module>
    trello_token = access_token['oauth_token']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
It gave me the Trello oauth tokens, but there was an error in the end (```TypeError: 'NoneType' object has no attribute '__getitem__'```).

(*It's not a problem that I'm showing the tokens here, since I created this Trello account specially for this test*)

I copied the oauth tokens into keys.py and ran ```python habitrello.py``` again:

```
Traceback (most recent call last):
  File "habitrello.py", line 324, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 280, in main
    self.setup_board()
  File "habitrello.py", line 227, in setup_board
    self.add_labels()
TypeError: add_labels() takes exactly 2 arguments (1 given)
```

It created a 'Habit RPG' board in Trello with the usual 'To do, Doing, Done' lists.

If I run it again (without changing the 'Habit RPG' board name), this is what I get:

```
Traceback (most recent call last):
  File "habitrello.py", line 324, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 282, in main
    self.get_labels()
  File "habitrello.py", line 261, in get_labels
    labels = self.board.get_labels()
AttributeError: 'Board' object has no attribute 'get_labels'
```

And this is what I get every time I run it again, unless I change the board name (i.e. habitrello can't find the board and creates it again), which then gives the first error ('TypeError: add_labels() takes exactly 2 arguments (1 given)').

--
I have no idea how to solve this, or if this is related to my own configuration or to the script. 
But if it's not the script, **could it be that maybe the date formats have something to do with it**?

I don't know how the Trello API works with dates, but I know there's no way for the user to change the date format: I used to get mm/dd/YY (*which annoyed me greatly*), for some months now I see dates in dd/mm/YY format, because Trello sees that I'm in Brazil (I don't know if through the browser or the IP address).

If I can be of any help solving this, I'd love to help.

Thanks,

Guto

**Comment by larssorenson** [comment]
Hey Guto,

I'll look into this more. I think I see a couple of bugs, if not the issue you're facing. I don't think it's the dates though, because of the error messages.


Thanks,
Lars

**Comment by larssorenson** [comment]
Hey Guto,

After looking at it, it appears that I forgot to make sure my fork of py-trello was up to date, so some of the functionality was missing from the GitHub repo.
I'm working on testing it, but I've updated the repository and everything seems to be lining up.

I'll let you know shortly if it seems to be working.

Thanks,
Lars

**Comment by larssorenson** [comment]
It appears to be working now. Can you try again?

Sorry for all of the confusion and troubles.

**Comment by gutogarrote** [comment]
Hey @larssorenson!

Not yet, but I'm sure we'll get there (by which I mean you will, thanks a lot for the effort!)

I had no boards named Habit RPG in Trello and ran it:
```
2015-07-08 19:15:33 - Processing Trello Dailies.
No Dailies to process.
2015-07-08 19:15:33 - Processing HabitRPG Dailies.
Traceback (most recent call last):
  File "habitrello.py", line 324, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 288, in main
    self.process_habit_dailies()
  File "habitrello.py", line 60, in process_habit_dailies
    card = self.dailies_list.add_card(daily["text"], daily_id, due=str(midnight))
AttributeError: 'NoneType' object has no attribute 'add_card'
```

It created the 'Habit RPG' board and the lists *'Dailies, Habits, Todos'*, no cards.

Than I created a few cards (*Dailies/Work, Dailies/Do this daily, Habits/Work, Todos/This one thing*) and ran the script:

```
2015-07-08 19:19:22 - Processing Trello Dailies.
2015-07-08 19:19:24 - Daily Work was created in Trello!
Traceback (most recent call last):
  File "habitrello.py", line 324, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 286, in main
```
2015-07-08 19:19:22 - Processing Trello Dailies.
2015-07-08 19:19:24 - Daily Work was created in Trello!
Traceback (most recent call last):
  File "habitrello.py", line 324, in <module>
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "habitrello.py", line 286, in main
    self.process_trello_dailies()
  File "habitrello.py", line 49, in process_trello_dailies
    if trello_checked(trello_daily):
  File "/Users/gutohernandes/Documents/code/habitrello-development/utils.py", line 34, in trello_checked
    return trello_card.checklists[0].items[0]["checked"]
IndexError: list index out of range
```

The lists and cards are all there, but the *Dailies/Work* has a description: e8dec5b4-9741-4395-9009-5e57a63003f3

That's what I get if I run it again.

Thanks!
I wish I could help you more!

**Comment by larssorenson** [comment]
Hey Guto,

Another set of changes that should target the newest issues you've run into. Sorry I can't work more on proactively finding these issues, busy life etc. But I appreciate you working through these corner cases and helping me smooth out the rough edges.

Thanks,
Lars

**Comment by gutogarrote** [comment]
Hey Lars,

don't worry, I'm willing to test it for as long as it takes!

With no boards named 'Habit RPG' in Trello, I ran ```sudo -H pip install --upgrade -r requirements.txt```and then ```python run.py``` and this is what I got:

```
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    main()
  File "run.py", line 43, in main
    habit.main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/__init__.py", line 293, in main
    self.setup_board()
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/__init__.py", line 238, in setup_board
    self.board = client.add_board(board_name)
NameError: global name 'client' is not defined
```

No boards were created in Trello.

**Comment by larssorenson** [comment]
Hey Guto,

Sorry, I found that after I posted my previous message. I also decided to rewrite a decent portion of the code, of course while we're debugging it, and put the fix in there. If you grab v0.3 it should work. Hopefully.

Thanks,
Lars

**Comment by gutogarrote** [comment]
**I think we're getting there!** :+1: 

I cleared the Trello boards and ran run.py:

```
2015-07-09 21:48:28 - Processing Trello Dailies.
2015-07-09 21:48:28 - Processing HabitRPG Dailies.
2015-07-09 21:48:30 - Daily Work was created in HabitRPG!
2015-07-09 21:48:32 - Daily And that thing there was created in HabitRPG!
2015-07-09 21:48:34 - Daily One more daily was created in HabitRPG!
2015-07-09 21:48:36 - Daily Check bank account was created in HabitRPG!
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 50, in main
    HabiTrello(api, client).main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/__init__.py", line 107, in main
    self.dailies.process()
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/tasks.py", line 22, in process
    self.process_habit()
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/dailies.py", line 46, in process_habit
    daily_checked = daily["completed"]
KeyError: 'completed'
```

The *Habit RPG* board was created and some Dailies as well, but the script escaped with the error.

Then I ran it again, leaving the *Habit RPG* board:
```
2015-07-09 21:56:22 - Processing Trello Dailies.
2015-07-09 21:56:26 - Processing HabitRPG Dailies.
2015-07-09 21:56:28 - Daily do one thing was created in HabitRPG!
2015-07-09 21:56:30 - Daily Do this thing here was created in HabitRPG!
2015-07-09 21:56:33 - Daily The seventh thing 7 was created in HabitRPG!
2015-07-09 21:56:34 - Daily Do another thing was created in HabitRPG!
2015-07-09 21:56:36 - Daily And one more thing was created in HabitRPG!
2015-07-09 21:56:36 - Processing Trello Habits.
2015-07-09 21:56:37 - Done!
2015-07-09 21:56:37 - Processing HabitRPG Habits.
2015-07-09 21:56:38 - Habit Productive Work (Click the pencil to edit) was created in HabitRPG!
2015-07-09 21:56:40 - Habit Eat Junk Food (Click the pencil to edit) was created in HabitRPG!
2015-07-09 21:56:42 - Habit Work was created in HabitRPG!
2015-07-09 21:56:44 - Habit Take the Stairs/Elevator (Click the pencil to edit) was created in HabitRPG!
2015-07-09 21:56:44 - Done!
2015-07-09 21:56:44 - Processing Trello Todos.
2015-07-09 21:56:44 - Done!
2015-07-09 21:56:44 - Processing HabitRPG Todos.
2015-07-09 21:56:46 - Todo It does not bring it back was created from HabitRPG!
2015-07-09 21:56:48 - Todo does it bring it back was created from HabitRPG!
2015-07-09 21:56:48 - Done!
```

**It worked!** :smile: 

The Dailies, Habits and Todos were created like they should!

So I tried checking some of the dailies and Todos as completed and the *'Work'* and *'Take the Stairs/Elevator (Click the pencil to edit)'* Habits as * Up*. I also created 2 new Todos in Trello, with due dates:
![habit_rpg___trello](https://cloud.githubusercontent.com/assets/4546773/8611227/12ea27da-2694-11e5-8fdc-ba0aa56ae1ff.png)

Than I ran run.py again:
```
2015-07-09 22:06:54 - Processing Trello Dailies.
2015-07-09 22:06:55 - Daily And that thing there was completed!
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 50, in main
    HabiTrello(api, client).main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/__init__.py", line 107, in main
    self.dailies.process()
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/tasks.py", line 21, in process
    self.process_trello()
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/dailies.py", line 35, in process_trello
    self.complete_task(self.dailies[trello_daily.description])
  File "/Users/gutohernandes/Documents/code/habitrello-development/habitrello/tasks.py", line 11, in complete_task
    task["completed"] = True
TypeError: 'Card' object does not support item assignment
```

So I guess if the board exists, it syncs from Habit RPG to Trello, but there's still some trouble syncing from Trello to Habit RPG.

I guess we're not far @larssorenson, thanks for the effort! :smiley:

**Comment by larssorenson** [comment]
Hey Guto,

Thanks for being so patient! Try v0.3.2. It should fix these two issues. I'm so glad that we're getting close! Sorry again for all of the trouble.

Thanks,
Lars

**Comment by larssorenson** [comment]
Hey @gutogarrote , I haven't heard from you in a while so I'm guessing you either gave up or it started working again.

I'm going to close this issue for now. If you're still having troubles feel free to open another.

Thanks for using this, let me know if you need anymore help!
