### ISSUE TITLE
Problems with trello interface

### ISSUE THREAD

**Issue by signaleleven** [larssorenson/habitrello#3]
Hi!
I don't know if you're still maintaining the project, but I'm having troubles using it.

It starts syncing (it creates one or two cards in trello based on the content of my habitrpg) but then it chokes.
It seems to be a problem with py-trello, rather than your code, but I would not know what to look at.
Since your fork of py-trello is a bit behind, I installed the original (from sarumont) but the result is identical.
Any idea?

```
signaleleven@Sorona:~/habitrello.py/habitrello$ python run.py
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 50, in main
    HabiTrello(api, client).main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "/home/signaleleven/habitrello.py/habitrello/habitrello/__init__.py", line 33, in __init__
    self.setup_lists()
  File "/home/signaleleven/habitrello.py/habitrello/habitrello/__init__.py", line 59, in setup_lists
    for board_list in self.board.get_lists('all'):
  File "/usr/local/lib/python2.7/dist-packages/trello/board.py", line 125, in get_lists
    query_params={'cards': 'none', 'filter': list_filter})
  File "/usr/local/lib/python2.7/dist-packages/trello/trelloclient.py", line 190, in fetch_json
    raise ResourceUnavailable("%s at %s" % (response.text, url), response)
trello.exceptions.ResourceUnavailable: Internal Server Error at https://api.trello.com/1/boards/561d31fa2e8d1f97276c41d7/lists (HTTP status: 500)
1 signaleleven@Sorona:~/habitrello.py/habitrello$ ls
habitrello  README.md  requirements.txt  run.py
signaleleven@Sorona:~/habitrello.py/habitrello$ python run.py --skip-dailies
2015-10-13 18:48:26 - Processing Trello Habits.
2015-10-13 18:48:26 - Done!
2015-10-13 18:48:26 - Processing HabitRPG Habits.
2015-10-13 18:48:31 - Habit Skip Meal was created in HabitRPG!
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 50, in main
    HabiTrello(api, client).main(args.skip_todos, args.skip_dailies, args.skip_habits)
  File "/home/signaleleven/habitrello.py/habitrello/habitrello/__init__.py", line 109, in main
    self.habits.process()
  File "/home/signaleleven/habitrello.py/habitrello/habitrello/tasks.py", line 22, in process
    self.process_habit()
  File "/home/signaleleven/habitrello.py/habitrello/habitrello/habits.py", line 52, in process_habit
    card.add_checklist("Up/Down", checklist_items, checklist_values)
  File "/usr/local/lib/python2.7/dist-packages/trello/card.py", line 380, in add_checklist
    self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/trello/card.py", line 148, in fetch
    self._checklists = self.fetch_checklists() if eager else None
  File "/usr/local/lib/python2.7/dist-packages/trello/card.py", line 172, in fetch_checklists
    '/cards/' + self.id + '/checklists', )
  File "/usr/local/lib/python2.7/dist-packages/trello/trelloclient.py", line 190, in fetch_json
    raise ResourceUnavailable("%s at %s" % (response.text, url), response)
trello.exceptions.ResourceUnavailable: Internal Server Error at https://api.trello.com/1/cards/561d35db5264b8efa8bfee54/checklists (HTTP status: 500)

```

**Comment by larssorenson** [comment]
Hey, thanks for the issue!

I am still maintaining this. Not proactively unfortunately, but I'll take a look at this later this evening. A preliminary glance seems to indicate that there's something wrong in the order that things are being done, or the py-trello library has something broken. Either way I should have an answer sometime tonight.

**Comment by larssorenson** [comment]
Hey @signaleleven,

Can you confirm for me the Trello board that was created, what version of HabiTrello you're using, and the version(s) of py-trello you used? I just ran with the latest of everything and it seemed to work no problem. According to the errors thrown, it looks like the board might not exist?
I'm not sure, it's odd to get a 500 from Trello using the library. I would expect a 404, 401, or 400.

Thanks.

**Comment by signaleleven** [comment]
I made a few more tests, and the error was happening at different stages.
Then I had no time to try again. Yesterday I did, without changing a single thing (other than deleting cards and archiving the lists already created) and everything worked. It seems that the problem was in the Trello API the day I tried...

**Comment by larssorenson** [comment]
No problem, I'm glad it's not my fault :P
